baseURL = "http://blog.gophergo.cn"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "IFLY's Site"
theme = "dream-plus"
themesDir = "./themes"   #Don't use this, only for exampleSite
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

disqusShortname = "dream-plus"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
  author = "IFLY"
  description = "A hub for my works."
  avatar = "/img/myavatar.jpg"
  motto = "A keen maker, programmer and an Instructables author."
  enableToc = true
  enableShareCard = true

  #Background settings
  enableColorBG= true

  #Post-displaying Settings
  enableTags = true
  enableCategories = true

  customCSS = ["/css/highlight.css"]

  #Cards shown per page
  itemsPerPage = 4

  #Enable card view
  contentType = "posts"

  #Enable Twitter Emoji
  twitterEmoji=true

[social]
  email = "edenzhong7@gmail.com"
  github = "ilgoat"
  stackoverflow = "ilgoat"
  medium = "ilgoat"
  twitter = "ilgoat"
  siteStartYear = 2018
